# Generated by Django 4.2.8 on 2023-12-18 19:00

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "Tops"),
                            (1, "Pants"),
                            (3, "Accessories"),
                            (3, "Artwork"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        choices=[
                            (0, "XS"),
                            (1, "S"),
                            (2, "M"),
                            (3, "L"),
                            (4, "XL"),
                            (5, "XXL"),
                        ],
                        default=0,
                    ),
                ),
                ("price", models.FloatField()),
                ("description", models.TextField()),
                (
                    "featured_image",
                    cloudinary.models.CloudinaryField(
                        default="placeholder", max_length=255, verbose_name="image"
                    ),
                ),
                ("image_alt", models.CharField(default="alt", max_length=100)),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Out of Stock"), (1, "In Stock")], default=0
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("body", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("approved", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "ordering": ["created_on"],
            },
        ),
    ]
