# Generated by Django 4.2.8 on 2023-12-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_category_delete_comment_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.IntegerField(
                choices=[
                    ("XS", 0),
                    (1, "S"),
                    (2, "M"),
                    (3, "L"),
                    (4, "XL"),
                    (5, "XXL"),
                ],
                default=0,
            ),
        ),
    ]
